[package]
name = "usbd-ctaphid"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

[dependencies]
# nom = { version = "5.0.1", default-features = false }
usb-device = "0.2.3"
cortex-m-semihosting = "0.3.5"
cortex-m-funnel = { version = "0.1.0-alpha.1", optional = true}
ufmt = { version = "0.1.0", optional = true}

[features]
logging = ["cortex-m-funnel", "ufmt"]
